### ISSUE TITLE
awk error in Manjaro linux

### ISSUE THREAD

**Issue by mobius41** [karli-sjoberg/gswitch#10]
When running 

- `sudo gswitch setup` 

I get the following error message.

```awk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator```

May be related to different versions of gawk.

- `gawk -V'

`GNU Awk 5.0.1, API: 2.0 (GNU MPFR 4.0.2, GNU MP 6.1.2)`

**Comment by mobius41** [comment]
Removing the backslash in line 9 of the gswitch script fixes the problem on my machine. 

```awk '/BusID/{gsub(/(PCI:|")/," ");print$2}' /etc/X11/xorg.conf.egpu```

**Comment by shervinsahba** [comment]
@mobius41 Thanks. That worked fine for me. Also on Manjaro.

**Comment by karli-sjoberg** [comment]
Hey guys!

I've heard if this before. It's because, for some reason, Ubuntu uses 'mawk' instead of 'gawk'

/K

**Comment by karli-sjoberg** [comment]
Noticed that I forgot to mention I "fixed" this issue :smile: 

85349342d4b17bd4f91778f318d08335bfd24525
