### ISSUE TITLE
Usage on Fedora 34 beta

### ISSUE THREAD

**Issue by He1nr1ch** [karli-sjoberg/gswitch#15]
Running Fedora 34 beta with Mutter. 
NVIDIA 2080Ti eGPU. 
I installed the RPMFusion NVIDIA drivers.
When trying to run gswitch I get the following error:
`[heinrich@fedorap72 ~]$ sudo gswitch egpu
/usr/bin/gswitch: line 12: lsb_release: command not found
You are now set up. Would you like to reload? (Y/n)
`
Choosing Y gets me two black screens.

**Comment by He1nr1ch** [comment]
I installed lsb_release and it ran. Sorta.

I still got two black screens.

**Comment by karli-sjoberg** [comment]
I think it's because Fedora has gone over to Wayland and this only works with Xorg. Can you choose to use that instead?
