### ISSUE TITLE
only high CPU load and black screen

### ISSUE THREAD

**Issue by frankenstein91** [karli-sjoberg/gswitch#4]
OS: Arch Linux x86_64
Kernel: 5.2.14-arch2-1-ARCH
Resolution: 3840x1080 @ 59.97Hz
CPU: Intel i7-8550U (8) @ 4.000GHz
GPU: Intel UHD Graphics 620
GPU: NVIDIA GeForce GTX 960
GPU Driver: NVIDIA 435.21

Unfortunately the X11 doesn't start anymore after the Config switch.
I can go to the terminal via Intel graphics.

**Comment by frankenstein91** [comment]
my lspci output

```
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers (rev 08)
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)
00:14.0 USB controller: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller (rev 21)
00:14.2 Signal processing controller: Intel Corporation Sunrise Point-LP Thermal subsystem (rev 21)
00:16.0 Communication controller: Intel Corporation Sunrise Point-LP CSME HECI #1 (rev 21)
00:17.0 SATA controller: Intel Corporation Sunrise Point-LP SATA Controller [AHCI mode] (rev 21)
00:1c.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #1 (rev f1)
00:1c.4 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #5 (rev f1)
00:1c.5 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #6 (rev f1)
00:1d.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #9 (rev f1)
00:1f.0 ISA bridge: Intel Corporation Sunrise Point LPC Controller/eSPI Controller (rev 21)
00:1f.2 Memory controller: Intel Corporation Sunrise Point-LP PMC (rev 21)
00:1f.3 Audio device: Intel Corporation Sunrise Point-LP HD Audio (rev 21)
00:1f.4 SMBus: Intel Corporation Sunrise Point-LP SMBus (rev 21)
01:00.0 PCI bridge: Intel Corporation JHL6340 Thunderbolt 3 Bridge (C step) [Alpine Ridge 2C 2016] (rev 02)
02:00.0 PCI bridge: Intel Corporation JHL6340 Thunderbolt 3 Bridge (C step) [Alpine Ridge 2C 2016] (rev 02)
02:01.0 PCI bridge: Intel Corporation JHL6340 Thunderbolt 3 Bridge (C step) [Alpine Ridge 2C 2016] (rev 02)
02:02.0 PCI bridge: Intel Corporation JHL6340 Thunderbolt 3 Bridge (C step) [Alpine Ridge 2C 2016] (rev 02)
03:00.0 System peripheral: Intel Corporation JHL6340 Thunderbolt 3 NHI (C step) [Alpine Ridge 2C 2016] (rev 02)
04:00.0 PCI bridge: Intel Corporation DSL6540 Thunderbolt 3 Bridge [Alpine Ridge 4C 2015]
05:01.0 PCI bridge: Intel Corporation DSL6540 Thunderbolt 3 Bridge [Alpine Ridge 4C 2015]
06:00.0 VGA compatible controller: NVIDIA Corporation GM206 [GeForce GTX 960] (rev a1)
06:00.1 Audio device: NVIDIA Corporation GM206 High Definition Audio Controller (rev a1)
3a:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTL8411B PCI Express Card Reader (rev 01)
3a:00.1 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 12)
3b:00.0 Network controller: Intel Corporation Wireless 8265 / 8275 (rev 78)
3c:00.0 Non-Volatile memory controller: Sandisk Corp WD Black 2018/PC SN520 NVMe SSD (rev 01)

```

**Comment by karli-sjoberg** [comment]
First of all, thank you for trying "gswitch", I'm thrilled to have people using it!

The distributions I have tested that works are basically Ubuntu (bionic,cosmic,disco), and derivatives have been known to work as well, like Xubuntu, Kubuntu, Mint, etc.

That said, I'd be happy to try and help you getting it working in Arch too but I don't have an install to test with. Would you be my guinea pig? :)

**Comment by frankenstein91** [comment]
Hello,
on weekends, I can step in as your guinea pig. I had once built a working solution at the Linux Days in Chemnitz with a known one. Unfortunately, this solution no longer works, so I became aware of your solution. Which also leads to the same error.
My configuration for Xorg looked a little different than yours.
```
Section "Module"
	Load "modesetting"
EndSection

Section "Device"
	Identifier "Device0"
	Driver "nvidia"
	BusID "PCI:6:0:0"
	Option "AllowEmptyConfiguration" "true"
	Option "AllowExternalGpus" "true"
EndSection


Section "Device"
	Identifier "Intel Grafik"
	Driver "modesetting"
	BusID "pci:00:02:0"
EndSection

```

In addition, I had a service running that did the switching at startup.
```
[Unit]
Description=adds/removes egpu config depening on presence
Before=graphical.target

[Service]
Type=oneshot
ExecStart=/bin/prepareegpuconfig.sh

[Install]
WantedBy=default.target
```

prepareegpuconfig.sh:
```
#!/usr/bin/env bash
if lspci | grep --quiet NVIDIA; then
echo "
Section "Module"
	Load "modesetting"
EndSection

Section "Device"
	Identifier "Device0"
	Driver "nvidia"
	BusID "PCI:6:0:0"
	Option "AllowEmptyConfiguration" "true"
	Option "AllowExternalGpus" "true"
EndSection
" > /etc/X11/xorg.conf.d/egpu.cfg
else
	rm -f /etc/X11/xorg.conf.d/egpu.cfg
fi

```
Also an udev rule for hotplug
`ACTION=="add", DEVPATH=="/devices/pci0000:00/0000:00:1c.0/0000:01:00.0/0000:02:01.0/0000:04:00.0/0000:05:01.0/0000:06:00.0/drm/card1", TAG+="systemd", RUN+="/bin/systemctl restart lightdm"`

It would be nice to get it working again.

**Comment by karli-sjoberg** [comment]
Hmm, I noticed from your output that you are putting the file in '/etc/X11/xorg.conf.d/' instead of mine that just puts it in '/etc/X11/'. Besides that, I don't see much difference with what 'gswitch' does compared to your solution. Try this out:
`# echo 'n' | gswitch egpu`
`# mv /etc/X11/xorg.conf /etc/X11/xorg.conf.d/egpu.cfg`
`# systemctl restart display-manager`

Is that better?

**Comment by frankenstein91** [comment]
Hello I tried my luck unsuccessfully. But I can say that the Webkit2 version of ligthdm was responsible for the high load when it came to the black screen. So we just need to figure out why I can't get a picture.
I connected the screen via Displayport to the external graphics card. But also the notebook screen and the display port of the notebooks remain black. For the other ports, I currently lack the cables.

**Comment by frankenstein91** [comment]
Do you have any idea what we can do?

**Comment by karli-sjoberg** [comment]
Ah, sorry, life happened, thanks for reminding me! :D Hmm, if you pastebin a failed X11 log, I can compare to my successful ones to see if there's something obvious! You could also register over at egpu.io to ask how arch folk have their config set up. Do both I'd say!:D

**Comment by frankenstein91** [comment]
i will try it as soon as possible 

It is hard to get the log with only the tty

**Comment by karli-sjoberg** [comment]
Den 3 okt. 2019 19:00 skrev frankenstein91 <notifications@github.com>:i will try it as soon as possible
It is hard to get the log with only the ttyIn Ubuntu, the last log is called:/var/log/Xorg.0.logAnd the second last is called:/var/log/Xorg.0.log.oldIsn't Arch rotating them like that as well? Then you would only need to fail one time, switch back and do the rest from X. Or you can just tar all the Xorg logs up and send :)/K

**Comment by frankenstein91** [comment]
I have a *.old on archeLinux as well. But i had no time to let it crash this weekend. you and my gpu are not forgotten

**Comment by karli-sjoberg** [comment]
Den 6 okt. 2019 16:56 skrev frankenstein91 <notifications@github.com>:I have a *.old on archeLinux as well. But i had no time to let it crash this weekend. you and my gpu are not forgottenNo worries, I'm around :)/K

**Comment by frankenstein91** [comment]
I had some time and was able to tinker with the problem again.
When switching I get an awk error message, but I think I already mentioned that. Nevertheless it is here again.

> awk: Kommandozeile:1: Warnung: regexp escape sequence `\"' is not a known regexp operator

And I backed up two log files, one without rebooting and one with rebooting. Both don't work.

[noReboot.txt](https://github.com/karli-sjoberg/gswitch/files/3720860/noReboot.txt)
[Reboot.txt](https://github.com/karli-sjoberg/gswitch/files/3720861/Reboot.txt)

Since it will be winter again, I hope that the problem will be solved soon and I can game again.

**Comment by karli-sjoberg** [comment]
That's wierd, that error shouldn't happen. I wonder what's causing it...Please run:# LC_ALL=C sh -x gswitch egpuThen switch back:# gswitch internalAnd pastebin the output so I can see where it bombs. Thanks in advance!/KDen 12 okt. 2019 17:57 skrev frankenstein91 <notifications@github.com>:I had some time and was able to tinker with the problem again.
When switching I get an awk error message, but I think I already mentioned that. Nevertheless it is here again.

awk: Kommandozeile:1: Warnung: regexp escape sequence `"' is not a known regexp operator

And I backed up two log files, one without rebooting and one with rebooting. Both don't work.
noReboot.txt
Reboot.txt
Since it will be winter again, I hope that the problem will be solved soon and I can game again.

**Comment by frankenstein91** [comment]
```
[root@ng ~]# LC_ALL=C sh -x gswitch egpu
++ whoami
+ '[' root '!=' root ']'
+ EGPU_TEMPLATE=/etc/X11/xorg.conf.egpu
++ awk '/BusID/{gsub(/(PCI:|\")/," ");print$2}'
awk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator
+ EGPU_BUS_ID=6:0:0
++ awk '/Driver/{gsub("\"","");print$2}'
+ XORG_DRIVER=nvidia
+ '[' -h /etc/X11/xorg.conf ']'
+ '[' -f /etc/X11/xorg.conf.egpu ']'
++ readlink /etc/X11/xorg.conf
+ '[' /etc/X11/xorg.conf.egpu = /etc/X11/xorg.conf.egpu ']'
+ EGPU_SET=true
+ case $1 in
+ switch_egpu
+ '[' true = true ']'
+ ask_reload 'You are already set up. Would you like to reload? (Y/n)'
+ QUESTION='You are already set up. Would you like to reload? (Y/n)'
+ echo 'You are already set up. Would you like to reload? (Y/n)'
You are already set up. Would you like to reload? (Y/n)
+ read ANSWER
n
+ case ${ANSWER} in
+ RELOAD=false
+ '[' false = true ']'
+ exit 0
[root@ng ~]# LC_ALL=C sh -x gswitch internal
++ whoami
+ '[' root '!=' root ']'
+ EGPU_TEMPLATE=/etc/X11/xorg.conf.egpu
++ awk '/BusID/{gsub(/(PCI:|\")/," ");print$2}'
awk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator
+ EGPU_BUS_ID=6:0:0
++ awk '/Driver/{gsub("\"","");print$2}'
+ XORG_DRIVER=nvidia
+ '[' -h /etc/X11/xorg.conf ']'
+ '[' -f /etc/X11/xorg.conf.egpu ']'
++ readlink /etc/X11/xorg.conf
+ '[' /etc/X11/xorg.conf.egpu = /etc/X11/xorg.conf.egpu ']'
+ EGPU_SET=true
+ case $1 in
+ switch_internal
+ '[' true = true ']'
+ rm -f /etc/X11/xorg.conf
+ ask_reload 'You are now set up. Would you like to reload? (Y/n)'
+ QUESTION='You are now set up. Would you like to reload? (Y/n)'
+ echo 'You are now set up. Would you like to reload? (Y/n)'
You are now set up. Would you like to reload? (Y/n)
+ read ANSWER
n
+ case ${ANSWER} in
+ RELOAD=false
+ '[' false = true ']'
+ exit 0
```

**Comment by frankenstein91** [comment]
and for the check i use GNU Awk 5.0.1, API: 2.0 (GNU MPFR 4.0.2, GNU MP 6.1.2)

**Comment by karli-sjoberg** [comment]
Ok, so it's just a warning and it finds the BUS ID anyway, so it's not the real issue here. Let me analyze the logs and get back to you, thanks!

/K

**Comment by karli-sjoberg** [comment]
You have to pastebin the logs, I cannot open them as attachments in a mail, they have to be linked. Just go to "pastebin.com", paste the logs there individually and reply with the links here, please. Thanks in advance!

/K

**Comment by frankenstein91** [comment]
On github the links are working great without problems. But here is a web page with the logs.

with reboot: https://paste.3server.de/?1d10deb37252bf58#LUExkmsAvkPbJpuDbHdPcHfqgIVZs3Pxnhzaueglwmk=

no reboot: https://paste.3server.de/?9e0dfaec644e6fb5#a3aVU1ZgaYit+pjHJTfyrA2+FjgoeWDRu8oIqxO2RHw=

**Comment by karli-sjoberg** [comment]
Oh, my bad, I am viewing through FastHub on Android. Thanks for the links though, I'll look them over and get back to you!

**Comment by frankenstein91** [comment]
just a side note:
@k0shk0sh is that FastHub problem known to you?

**Comment by k0shk0sh** [comment]
@frankenstein91 what problem are you referring to?

**Comment by frankenstein91** [comment]
The great developer, who helps me with my problem, uses the App FastHub. But he can't load the attachments (https://github.com/karli-sjoberg/gswitch/issues/4#issuecomment-541350616), at least that's how I understood it. To make it easier for him to work on our problem, I wanted to ask you, as the developer of FastHub, if you know this.

**Comment by k0shk0sh** [comment]
I could easily click on the links and it opens the browser. Not sure what's the problem here for him.

**Comment by frankenstein91** [comment]
sorry @k0shk0sh I have set the wrong link :(
He has problems with https://github.com/karli-sjoberg/gswitch/issues/4#issuecomment-541337596

**Comment by k0shk0sh** [comment]
@frankenstein91 owh yeah, aware of that

**Comment by karli-sjoberg** [comment]
So I have looked at the logs you supplied and I just have an observation I find...odd. Probably nothing, I just found it strange. Maybe you can explain why this happens. Without reboot, this happens:

```
[   421.458] (II) Loading sub module "glxserver_nvidia"
[   421.458] (II) LoadModule: "glxserver_nvidia"
[   421.458] (II) Loading /usr/lib/nvidia/xorg/libglxserver_nvidia.so
[   421.500] (II) Module glxserver_nvidia: vendor="NVIDIA Corporation"
```

But with a reboot, it says:

```
[     9.263] (II) Loading sub module "glxserver_nvidia"
[     9.263] (II) LoadModule: "glxserver_nvidia"
[     9.263] (WW) Warning, couldn't open module glxserver_nvidia
[     9.263] (EE) NVIDIA: Failed to load module "glxserver_nvidia" (module does not exist, 0)
```

Now, it's probably not the core issue but it certainly can't be helpful :) How are you authorizing thunderbolt on your system?

**Comment by karli-sjoberg** [comment]
BTW, I think I know why you have that wierd awk error. Apparently, Ubuntu is using 'mawk' for some reason:

```
$ awk -W version
mawk 1.3.3 Nov 1996, Copyright (C) Michael D. Brennan
...
```

Probably explains that, at least :)

**Comment by frankenstein91** [comment]
I have now clue for the error message, sorry.

> Now, it's probably not the core issue but it certainly can't be helpful :) How are you authorizing thunderbolt on your system?

I have used tbadm for that

```
sudo tbtadm devices
0-1     Sonnet Technologies, Inc.       eGFX Breakaway Box      authorized      in ACL

sudo tbtadm topology
Controller 0
    ├─ Details:
    │   ├─ Name: N130WU, Clevo
    │   └─ Security level: SL1 (user)
    │
    └─ eGFX Breakaway Box, Sonnet Technologies, Inc.
        └─ Details:
            ├─ Route-string: 0-1
            ├─ Authorized: Yes
            ├─ In ACL: Yes
            └─ UUID: 37896966-f1c4-11e9-81b4-2a2ae2dbcce4

sudo tbtadm acl
37896966-f1c4-11e9-81b4-2a2ae2dbcce4    Sonnet Technologies, Inc.       eGFX Breakaway Box      connected

```

**Comment by karli-sjoberg** [comment]
What if the tbtadm "stuff" happens after gswitch?

Not that I'm recommending you to have this permanently, but as a test, what happens if you deploy that ugly, insecure 'udev' rule I have? Would you be willing to test that?

If it works, it may be "just" a race condition we can work around.

**Comment by frankenstein91** [comment]
Shouldn't that matter when restarting the display manager? And tbtadm is from @intel. You can give it a try from https://github.com/intel/thunderbolt-software-user-space.
But i will test it.

**Comment by frankenstein91** [comment]
unfortunately I haven't yet come to a test due to my work and leave Germany for 3 weeks. Please leave the ticket open.

**Comment by karli-sjoberg** [comment]
Yes, of course man, absolutely! No worries, I'll keep it open!

**Comment by frankenstein91** [comment]
Unfortunately udev doesn't help either.

**Comment by shervinsahba** [comment]
> I had some time and was able to tinker with the problem again.
> When switching I get an awk error message, but I think I already mentioned that. Nevertheless it is here again.
> 
> > awk: Kommandozeile:1: Warnung: regexp escape sequence `"' is not a known regexp operator
> 
> And I backed up two log files, one without rebooting and one with rebooting. Both don't work.
> 
> [noReboot.txt](https://github.com/karli-sjoberg/gswitch/files/3720860/noReboot.txt)
> [Reboot.txt](https://github.com/karli-sjoberg/gswitch/files/3720861/Reboot.txt)
> 
> Since it will be winter again, I hope that the problem will be solved soon and I can game again.

I have the same `awk` warning on Manjaro 4.19 with GNU Awk 5.0.1. It doesn't really affect functionality for me, so I ignore it. My gswitch isn't the bleeding edge version, but it's fairly recent, as I set it up in October. 

I do seem to need to operate `gswitch` and connect my eGPU in a specific order to prevent a black screen. It's been a month since I've used it, but I can post more of my experience if it'll help troubleshoot.

**Comment by frankenstein91** [comment]
@shervinsahba please post your experience and your "specific order".

Thank you

**Comment by frankenstein91** [comment]
@shervinsahba are you still on github?

**Comment by shervinsahba** [comment]
Hi, yes! I have been traveling and have only recently returned. I'll try to
check it out this next week.

**Comment by frankenstein91** [comment]
is there something new on this problem?

**Comment by shervinsahba** [comment]
@frankenstein91 Sorry for the major delay. My hard disk failed, life happened, and now the world is on fire :) Anyway...

With the updated `gswitch`, most functionality works as it should be for me. I still get the `awk` ~~error~~ warning upon switching in either direction:

```awk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator```

Running `sudo switch egpu` and reloading fails for me. I get a black screen. 

However a reboot gets it running correctly, and I can then access my egpu by specifying a `DRI_PRIME=1` env variable prior to running commands. Disconnecting my egpu is fine, and upon reboot, the xorg settings revert to the internal card.

Running `sudo switch internal` works for me as intended.

**Comment by frankenstein91** [comment]
Hi...

could it be, that this makes the problem?
/etc/X11/xorg.conf.d/10-monitor.conf
```

Section "Monitor"
    Identifier "HDMI-1"
    Modeline "3840x1080"  266.50  3840 3888 3920 4000  1080 1083 1093 1111 +hsync -vsync
    Option "PreferredMode" "3840x1080"
EndSection
```

**Comment by karli-sjoberg** [comment]
No response from user, closing.

**Comment by frankenstein91** [comment]
the last update was from me... but it is okay, I switched hardware.
